DEFAULT:
  perform_check: yes
  allowed_licenses:
    - Apache-2.0
    - MIT
  license_for_new_files: Apache-2.0
  new_notice_python: |
    """
    SPDX-FileCopyrightText: © 2024 Tenstorrent Inc.

    SPDX-License-Identifier: {license}
    """

  espressif_copyright: '© 2024 Tenstorrent Inc.'

  include:
    - "*.py"

ignore:
  perform_check: no
  include:
    - .github/*
    - __pycache__
    - /benchmark/models/falcon/utils/configuration_RW.py
    - /CONTRIBUTING.md
    - /MAINTAINERS.md
