name: Validate SPDX License year in currently changed Python Files

on:
  pull_request:
    branches: [main]
    types:
      - opened
      - reopened
      - synchronize
      - assigned
      - review_requested

jobs:
  check-spdx-license:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Identify changed Python files and check licenses
        id: check-licenses
        run: |
          echo "current_year=$(date +"%Y")" >> $GITHUB_ENV  # Set current year as an environment variable
          missing_license_files=""
          for file in $(git diff --name-only HEAD^ HEAD | grep '\.py$'); do
            if ! grep -L "SPDX-License-Identifier: Apache-2.0" "$file" | grep -q "$current_year"; then
              missing_license_files="$missing_license_files$file\n"
            fi
          done
          echo "missing_license_files=$missing_license_files" >> $GITHUB_ENV  # Export the list of files

      - name: Comment on PR about missing SPDX licenses
        if: env.missing_license_files != ''
        uses: actions/github-script@v6
        with:
          script: |
            const issueNumber = context.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const missingFiles = process.env.missing_license_files.trim();
            const currentYear = process.env.current_year;
            const commentBody = `The following Python files are missing the correct SPDX license year or do not contain the '${currentYear}' year within their license header:\n\`\`\`\n${missingFiles}\`\`\`\nPlease update the files accordingly. Your attention and cooperation in this matter are greatly appreciated.\n Thank you.`;
            
            github.rest.issues.createComment({
              issue_number: issueNumber,
              owner: owner,
              repo: repo,
              body: commentBody
            });

      - name: Fail the workflow
        if: env.missing_license_files != ''
        run: |
          echo "Failing the workflow due to non-compliance with SPDX license requirements."
          exit 1
