name: Validate SPDX License year and company mention in currently changed Python Files

on:
  pull_request:
    branches: [main]
    types:
      - opened
      - reopened
      - synchronize
      - assigned
      - review_requested

jobs:
  check-spdx-license:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Identify changed Python files and check licenses
        id: check-licenses
        run: |
          echo "current_year=$(date +"%Y")" >> $GITHUB_ENV  # Set current year as an environment variable
          missing_license_files=""
          incorrect_mention_files=""
          for file in $(git diff --name-only HEAD^ HEAD | grep '\.py$'); do
            # Check if file contains SPDX license and the current year
            if ! (grep -q "SPDX-License-Identifier: Apache-2.0" "$file" && grep -q "$current_year" "$file"); then
              missing_license_files="$missing_license_files$file "
            fi
            # Check if file contains the exact mention "2024 Tenstorrent AI ULC"
            if ! grep -q "2024 Tenstorrent AI ULC" "$file"; then
              incorrect_mention_files="$incorrect_mention_files$file "
            fi
          done
          echo "missing_license_files=$missing_license_files" >> $GITHUB_ENV
          echo "incorrect_mention_files=$incorrect_mention_files" >> $GITHUB_ENV
          echo "Checked files for SPDX-License compliance and correct company mention."

      - name: Comment on PR about missing SPDX licenses or incorrect company mention
        if: env.missing_license_files != '' || env.incorrect_mention_files != ''
        uses: actions/github-script@v6
        with:
          script: |
            const issueNumber = context.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const missingFiles = process.env.missing_license_files.trim().replace(/\s+/g, '\n');
            const incorrectMentionFiles = process.env.incorrect_mention_files.trim().replace(/\s+/g, '\n');
            const currentYear = process.env.current_year;
            let commentBody = `Please review the following issues:\n`;
            if (missingFiles.length > 0) {
              commentBody += `The following Python files are missing the correct SPDX license year or do not contain the '${currentYear}' year within their license header:\n\`\`\`\n${missingFiles}\n\`\`\`\n`;
            }
            if (incorrectMentionFiles.length > 0) {
              commentBody += `The following files do not contain the correct 'Tenstorrent AI ULC' company name within thier license header:\n\`\`\`\n${incorrectMentionFiles}\n\`\`\`\n`;
            }
            commentBody += `Please update the files accordingly. Your attention and cooperation in this matter are greatly appreciated.\nThank you.`;
            
            github.rest.issues.createComment({
              issue_number: issueNumber,
              owner: owner,
              repo: repo,
              body: commentBody
            });

      - name: Fail the workflow if issues are found
        if: env.missing_license_files != '' || env.incorrect_mention_files != ''
        run: |
          echo "Failing the workflow due to non-compliance with SPDX license requirements and incorrect company mention."
          exit 1
