name: Validate SPDX License year and company mention in currently changed Python Files

on:
  pull_request:
    branches: [main]
    types:
      - opened
      - reopened
      - synchronize
      - assigned
      - review_requested

jobs:
  check-spdx-license:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Identify changed Python files and check licenses
        id: check-licenses
        run: |
          current_year="2024"  # Statically set current year for checking
          missing_license_files=""
          incorrect_mention_files=""
          for file in $(git diff --name-only HEAD^ HEAD | grep '\.py$'); do
            # Check if file contains the correct SPDX license identifier and the exact copyright statement
            if ! grep -q "SPDX-License-Identifier: Apache-2.0" "$file" || ! grep -q "SPDX-FileCopyrightText: © ${current_year} Tenstorrent AI ULC" "$file"; then
              missing_license_files="$missing_license_files$file "
            fi
          done
          echo "missing_license_files=$missing_license_files" >> $GITHUB_ENV
          echo "Checked files for correct SPDX-License compliance."

      - name: Comment on PR about incorrect SPDX licenses
        if: env.missing_license_files != ''
        uses: actions/github-script@v6
        with:
          script: |
            const issueNumber = context.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const missingFiles = process.env.missing_license_files.trim().replace(/\s+/g, '\n');
            const commentBody = `The following Python files are not compliant with the required licensing standards for 2024 or do not contain the correct copyright text 'Tenstorrent AI ULC' within their license header:\n\`\`\`\n${missingFiles}\n\`\`\`\nPlease update the files accordingly. Your attention and cooperation in this matter are greatly appreciated.\nThank you.`;
            
            github.rest.issues.createComment({
              issue_number: issueNumber,
              owner: owner,
              repo: repo,
              body: commentBody
            });

      - name: Fail the workflow if license issues are found
        if: env.missing_license_files != ''
        run: |
          echo "Failing the workflow due to non-compliance with SPDX license requirements."
          exit 1
