name: "l-checker workflow"

on:
  pull_request:
    branches:
      - "main"
    types:
      - opened
      - reopened
      - synchronize
      - assigned
      - review_requested

jobs:
  check-spdx-licenses:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install infra dependencies
        run: |
          python -m pip install git+https://github.com/espressif/check-copyright.git@master

      - name: Check SPDX licenses
        id: check-licenses
        run: |
          set +e
          output=$(python -m check_copyright --verbose --dry-run --replace --config ./check_copyright_config.yaml . | awk '/Some files are without a copyright note and a license header needs to be added:/,/^\s*$/')

          exit_code=$?
          echo "$output"  # Print output regardless of exit code
          echo "SPDX_LICENSE_CHECK_OUTPUT=$output" >> $GITHUB_STATE
          echo "SPDX_LICENSE_CHECK_EXIT_CODE=$exit_code" >> $GITHUB_STATE
          if [ $exit_code -eq 1 ]; then
            echo "SPDX license check failed with exit code $exit_code ***************"
            exit 0  # We exit with code 0 to ensure the workflow continues
          fi

      - name: Post comment if issues found
        id: print-then
        run: echo "::set-output name=output::$GITHUB_STATE"

      - name: Comment
        uses: actions/github-script@v6
        with:
          script: |
            const output = ${{ toJson(steps.print-then.outputs.output) }};
            const licenseOutput = output.SPDX_LICENSE_CHECK_OUTPUT;
            const issueNumber = context.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            if (licenseOutput) {
              const commentBody = `Checking SPDX licenses failed. Please check the files and add the missing SPDX licenses:\n\n${licenseOutput}`;
              github.rest.issues.createComment({
                issue_number: issueNumber,
                owner: owner,
                repo: repo,
                body: commentBody
              });
            }
