name: "l-checker workflow"

on:
  pull_request:
    branches:
      - "main"
    types:
      - opened
      - reopened
      - synchronize
      - assigned
      - review_requested

jobs:
  check-spdx-licenses:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
          cache: 'pip'
          cache-dependency-path: infra/requirements-infra.txt
      
      - name: Install infra dependencies
        run: |
          python -m pip install git+https://github.com/espressif/check-copyright.git@master
      
      - name: Check SPDX licenses
        id: check-licenses
        run: |
          output=$(python -m check_copyright --verbose --dry-run --config ./check_copyright_config.yaml .)
          echo "::set-output name=output::$output"
          echo "$output" | grep -E "Not an Espressif|Some files are without a copyright note" > errors.txt || true
      
      - name: Post comment if issues found
        if: steps.check-licenses.outputs.output != ''
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            if (fs.existsSync('errors.txt')) {
              const errors = fs.readFileSync('errors.txt', 'utf8');
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: errors
              });
            }
