name: "l-checker workflow"

on:
  pull_request:
    branches:
      - "main"
    types:
      - opened
      - reopened
      - synchronize
      - assigned
      - review_requested

jobs:
  check-spdx-licenses:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install infra dependencies
        run: |
          python -m pip install git+https://github.com/espressif/check-copyright.git@master

      - name: Check SPDX licenses
        id: check-licenses
        run: |
          set +e
          output=$(python -m check_copyright --verbose --dry-run --replace --config ./check_copyright_config.yaml . | grep -E 'Some files are without a copyright note and a license header needs to be added:')
          exit_code=$?
          echo "$output"  # Print output regardless of exit code
          set -e
          # echo "::set-output name=output::$output"
          if [ $exit_code -eq 1 ]; then
            echo "SPDX license check failed with exit code $exit_code *************** will be printed in next step"
            # echo "$output"
            exit 0  # We exit with code 0 to ensure the workflow continues
          fi

      - name: Post comment if issues found
        id: print-then
        run: echo "${{ steps.check-licenses.outputs.output }}"

