name: SPDX License Check

on:
  pull_request:
    branches:
      - main

jobs:
  check-licenses:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install check-copyright

      - name: Run SPDX License Check
        run: |
          output=$(python -m check_copyright --verbose --dry-run --replace --config ./check_copyright_config.yaml .)
          echo "$output"
          echo "::set-output name=failed_files::$output"
          exit_code=$?
          if [ $exit_code -eq 1 ]; then
            echo "SPDX license check failed with exit code $exit_code"
            exit 0  # Continue workflow despite failure
          fi

  capture-files:
    needs: check-licenses
    runs-on: ubuntu-latest
    steps:
      - name: Output failed files
        run: |
          echo "Failed files: ${{ needs.check-licenses.outputs.failed_files }}"
