name: Check License Headers

on:
  pull_request:
    branches:
      - main
  push:

jobs:
  check_license:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}

      - name: Get changed .py files
        id: changed-files
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
              changed_files=$(git diff --name-only -r HEAD^1 HEAD | grep "\.py$" | xargs)
          else
              changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep "\.py$" | xargs)
          fi
          echo "::set-output name=changed_files::$changed_files"

      - name: List changed .py files
        run: |
          echo "Changed .py files:"
          for file in ${{ steps.changed-files.outputs.changed_files }}; do
              echo "$file"
          done
